[[chap08]]
== Strings

Strings não são como inteiros, pontos flutuante, e tipos booleanos. Uma string é uma _sequência_, o que significa que ela está em uma coleção ordenada de outros valores. Neste capítulo você verá como acessar os caracteres que compõem uma string, e você irá aprender sobre algumas funções auxiliares de strings fornecidas pelo Julia.
(((string)))(((sequência)))

[[characters]]
=== Caracteres

Falantes da língua portuguesa estão familiarizados com caracteres como as letras do alfabeto (A, B, C, ...), numerais, e a pontuação comum. Esses caracteres são padronizados e mapeados para valores inteiros entre 0 e 127 pelo _padrão ASCII_ (American Standard Code for Information ou "Código Padrão Americano de Intercâmbio de Informações")
(((padrão ASCII)))

Existem, é claro, muitos outros caracteres usados em línguas diferentes do Português, incluindo variantes dos caracteres ASCII com acentos e outras modificações, scripts relacionados como o Cirílico e o Grego, e scripts completamente não relacionados ao ASCII e ao Português, incluindo Árabe, Chinês, Hebreu, Hindi, Japonês, e Koreano.
O _padrão Unicode_ lida com as complexidades do que exatamente é um caractere, e é geralmente aceitado como o padrão definitivo que resolve esse problema. Ele fornece um número único para todo caractere em uma escala mundial.
(((padrão Unicode)))

Um valor +Char+ representa um único caractere e está cercado por aspas únicas:
(((Char)))((("tipo", "Base", "Char", see="Char")))

[source,@julia-repl-test]
----
julia> 'x'
'x': ASCII/Unicode U+0078 (category Ll: letra, lowercase)
julia> '🍌'
'🍌': Unicode U+1F34C (category So: Symbol, other)
julia> typeof('x')
Char
----

Até mesmo emojis fazem parte do padrão Unicode. (*+\:banana: TAB+*)
(((emoji)))


=== Uma string é uma sequência

Uma string é uma sequência de caracteres. Você pode acessar os caracteres um de cada vez com o operador colchetes:
(((string)))(((String)))(((sequência)))(((operador colchetes)))((("[]", see="operador colchetes")))((("operador", "Base", "[]", see="operador colchetes")))

[source,@julia-repl-test chap08]
----
julia> fruta = "banana"
"banana"
julia> letra = fruta[1]
'b': ASCII/Unicode U+0062 (category Ll: letter, lowercase)
----

A segunda declaração seleciona o caractere número 1 de +fruta+ e o atribui para +letra+.

A expressão em colchetes é chamada de _indíce_. O indíce indica qual caractere da sequência você deseja (por isso o nome).
(((indíce)))

Toda indexação no Julia começa em 1, o primeiro elemento de qualquer objeto inteiramente indexado é encontrado no indíce 1 e o último no indíce +end+:
(((end)))

[source,@julia-repl-test chap08]
----
julia> fruta[end]
'a': ASCII/Unicode U+0061 (category Ll: letra, lowercase)
----

Você pode usar como indíce uma expressão que contém variáveis e operadores:

[source,@julia-repl-test chap08]
----
julia> i = 1
1
julia> fruta[i+1]
'a': ASCII/Unicode U+0061 (category Ll: letter, lowercase)
julia> fruta[end-1]
'n': ASCII/Unicode U+006E (category Ll: letter, lowercase)
----

Mas o valor do indíce precisa ser um inteiro. Caso contrário você recebe:
(((MethodError)))((("erro", "Core", "MethodError", see="MethodError")))

[source,@julia-repl-test chap08]
----
julia> letra = fruta[1.5]
ERROR: MethodError: no method matching getindex(::String, ::Float64)
----


=== +length+
+length+ é uma função embutida que retorna o número de caracteres em uma string:
(((length)))

[source,@julia-repl-test chap08]
----
julia> frutas = "🍌 🍎 🍐"
"🍌 🍎 🍐"
julia> len = length(frutas)
5
----

Para obter a última letra da string, você pode ficar tentado a fazer algo como:

[source,@julia-repl-test chap08]
----
julia> last = frutas[len]
' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
----

Mas você pode não conseguir o que espera.

Strings são codificadas usando a _codificação UTF-8_. UTF-8 é uma codificação de largura variável, o que significa que nem todos os caracteres estão codificados com o mesmo número de bytes.
(((codificação UTF-8)))

A função +sizeof+ retorna o número de bytes em uma string:
(((sizeof)))((("função", "Base", "sizeof", see="sizeof")))

[source,@julia-repl-test chap08]
----
julia> sizeof("🍌")
4
----

Como um emoji é codificado em 4 bytes e a indexação de strings é baseado em bytes, o quinto elemento de +frutas+ é um +ESPAÇO+.
(((emoji)))

Isso significa também que nem todo indíce de bytes em uma string UTF-8 é necessariamente um indíce válido para um caractere. Se você indexar em uma string com um indíce de bytes inválido, será gerado um erro:
(((StringIndexError)))((("erro", "Base", "StringIndexError", see="StringIndexError")))

[source,@julia-repl-test chap08]
----
julia> frutas[2]
ERROR: StringIndexError("🍌 🍎 🍐", 2)
----

No caso de +frutas+, o caractere +🍌+ é um caractere de quatro bytes, então os indíces 2,3 e 4 são inválido e o indíce do próximo caractere é 5; esse próximo indíce válido pode ser calculado por +nextind(frutas, 1)+, e o indíce depois dele por +nextind(frutas, 5)+ e assim por diante.
(((nextind)))((("função", "Base", "nextind", see="nextind")))


=== Travessia

Muitos cálculos envolvem o processamento de uma string, um caractere de cada vez. Comumente eles começam no início, selecionando cada caractere por vez, fazendo algo com ele, e continuando até o final. Esse padrão de processamento é denominado de _travessia_. Um jeito de escrever uma travessia é com um loop +while+:
(((travessia)))(((declaração while)))

[source,@julia-setup chap08]
----
indíce = firstindex(frutas)
while indíce <= sizeof(frutas)
    letra = frutas[indíce]
    println(letra)
    global indíce = nextind(frutas, indíce)
end
----

Esse loop faz a travessia da string e exibe cada letra em uma linha por si só. A condição do loop é +index pass:[&lt;=] sizeof(fruta)+, então quando o indíce é maior que o número de bytes em uma string, a condição é +false+, e o corpo do loop não executa.

A função +firstindex+ retorna o primeiro indíce de bytes válido. A palavra-chave +global+ antes de +indíce+ indica que nós queremos re-atribuir a variável +indíce+ definida em +Main+ (ver <<global_variables>>).
(((global)))(((firstindex)))((("função", "Base", "firstindex", see="firstindex")))

===== Exercício 8-1

Escreva uma função que recebe uma string como argumento e exibe as letras ao contrário, uma por linha.

Outro jeito de escrever uma travessia é com o loop +for+:
(((declaração for)))(((in)))

[source,@julia-setup chap08]
----
for letra in frutas
    println(letra)
end
----

Cada vez que o loop é percorrido, o próximo caractere na string é atribuido para a variável +letra+. O loop continua até que não hajam mais caracteres sobrando.

O próximo exemplo mostra como usar concatenação (multiplicação de strings) e um loop +for+ para gerar séries abecedárias (isto é, em ordem alfabética). No livro de Robert McCloskey, _Make way for Ducklings_ (Abra caminho para os patinhos), os nomes dos patinhos são Jack, Kack, Lack, Mack, Nack, Ouack, Pack, e Quack. Esse loop gera os nomes em ordem:

[source,@julia chap08-3]
----
prefixos = "JKLMNOPQ"
sufixo = "ack"

for letra in prefixos
    println(letra * sufixo)
end
----

É claro, isto não está completamente correto pois, “Ouack” E “Quack” estão incorretos.

===== Exercício 8-2

Modifique o programa para consertar esse erro.


=== Fatias de Strings

Um segmento de uma string é chamado de _fatia_. Selecionar uma fatia é similar a selecionar um caractere:
(((fatia)))

[source,@julia-repl-test chap08]
----
julia> str = "Júlio César";

julia> str[1:5]
"Júlio"
----

O operador +[n:m]+ retorna a parte da string do +n+-ésimo byte até o +m+-ésimo byte. Então o mesmo cuidado é necessário como para a indexação simples.
(((operador colchetes)))

A palavra-chave +end+ pode ser usada para indicar o último byte da string:
(((end)))

[source,@julia-repl-test chap08]
----
julia> str[8:end]
"Caesar"
----

Se o primeiro indíce é maior que o segundo, o resultado é uma _string vazia_, representada por duas aspas:
(((string vazia)))((("&quot;&quot;", see="string vazia")))

[source,@julia-repl-test chap08]
----
julia> str[8:7]
""
----

Uma string vazia não contém nenhum caractere e possui tamanho 0, mas diferente disso, é igual a qualquer outra string.

===== Exercício 8-3

Continuando este exemplo, o que você acha que +str[:]+ significa? Experiemente e veja.


=== String são Imutáveis

É tentador usar o operador +[]+ no lado esquerdo da atribuição, com a intenção de mudar um caractere de uma string. Por exemplo:
(((operador colchetes)))(((MethodError)))

[source,@julia-repl-test chap08]
----
julia> cumprimento = "Olá, Mundo!"
"Olá, Mundo!"
julia> cumprimento[1] = 'E'
ERROR: MethodError: no method matching setindex!(::String, ::Char, ::Int64)
----

O motivo deste erro é de que strings são _imutáveis_, o que significa que você não pode mudar uma string existente. O melhor que você pode fazer é criar uma nova string que é uma variação da original:
(((imutável)))

[source,@julia-repl-test chap08]
----
julia> cumprimento = "E" * cumprimento[2:end]
"Elá, Mundo!"
----

Esse exemplo concatena uma nova primeira letra em uma fatia de cumprimento. Ele não tem efeito algum na string original.


=== Interpolação de Strings

Construir strings usando concatenação pode vir a ser um incómodo. Para reduzir a necessidade dessas chamadas verbosas para +string+ ou multiplicações repetidas, O Julia permite _interpolação de strings_ usando +$+:
(((interpolação de strings)))((("$", see="interpolação de strings")))

[source,@julia-repl-test]
----
julia> cumprimento = "Olá"
"Olá"
julia> quem = "Mundo"
"Mundo"
julia> "$cumprimento, $(quem)!"
"Olá, Mundo!"
----

Isso é mais legível e conveniente do que concatenação de strings: +pass:[cumprimento * ", " * quem * "!"]+

O valor da menor expressão inteira após o +$+ é tomado como o valor que deve ser interpolado na sequência. Assim, você pode interpolar qualquer expressão em uma string usando parênteses:

[source,@julia-repl-test]
----
julia> "1 + 2 = $(1 + 2)"
"1 + 2 = 3"
----

[[searching]]
=== Buscando

O que a função a seguir faz?
(((buscar)))((("função", "definido pelo programador", "buscar", see="buscar")))

[source,@julia-setup]
----
function buscar(palavra, letra)
    indíce = firstindex(palavra)
    while indíce <= sizeof(palavra)
        if palavra[indíce] == letra
            return indíce
        end
        indíce = nextind(palavra, indíce)
    end
    -1
end
----

De certo modo, buscar é o inverso do operador +[]+. Ao invés de pegar um indíce e extrair o caractere correspondente, ela recebe o caractere e busca o indíce aonde este caractere aparece. Se o caractere não é achado, a função retorna -1.

Esse é o primeiro exemplo que nós vimos de uma declaração return dentro de um loop. Se +palavra[indíce] == letra+, a função sai do loop e retorna imediatamente.

Se o caractere não aparece na string, o programa sai do loop normalmente e retorna -1.

Esse padrão de computação-percorrendo a sequência e retornando quando achamos o que estamos procurando-é chamado de _busca_.
(((busca)))

===== Exercício 8-4

Modifique +busca+ para que ela tenha um terceiro parâmetro, o indíce em +palavra+ aonde ela deve começar a procurar.


[[looping_and_counting]]
=== Dando loop e contando

O seguinte programa conta o número de vezes que a letra +a+ aparece em uma string:

[source,@julia-setup]
----
palavra = "banana"
countador = 0
for letra in palavra
    if letra == 'a'
        global contador = contador + 1
    end
end
println(contador)
----

Esse programa demonstra outro padrão de computação chamado _contador_. A variável +contador+ é inicializada com 0 e incrementada toda vez que um +a+ é achado. Quando a função sai do loop, +contador+ contém o resultado-o número total de +a+’s.
(((contador)))

===== Exercício 8-5

Encapsule esse código em uma função chamada +conte+, e a generealize para que ela aceite a string e a letra como argumentos.

Depois reescreva a função de modo que ao invés de percorrer a string, ela usa a versão com três parâmetros de +busca+ da seção anterior.


=== Biblioteca String

O Julia fornece funções que executam uma variedade de operações utéis com strings. Por exemplo, a função +uppercase+ recebe uma string e retorna uma nova string com todas suas letras maiúsculas.
(((maiúscula)))((("função", "Base", "maiúscula", see="maiúscula")))

[source,@julia-repl-test]
----
julia> uppercase("Olá, Mundo!")
"OLÁ, MUNDO!"
----

Acontece que, existe uma função chamada +findfirst+ que é bastante similar a função +busca+ que nós escrevemos:
(((findfirst)))((("função", "definido pelo programador", "findfirst", see="findfirst")))

[source,@julia-repl-test]
----
julia> findfirst("a", "banana")
2:2
----

Na verdade, a função +findfirst+ é mais geral que a nossa função; ela pode achar substrings, não apenas caracteres:

[source,@julia-repl-test]
----
julia> findfirst("na", "banana")
3:4
----

Por padrão, +findfirst+ começa no início da string, mas a função +findnext+ recebe um terceiro argumento, o +indíce+ onde ela deve começar:
(((findnext)))((("função", "definido pelo programador", "findnext", see="findnext")))

[source,@julia-repl-test]
----
julia> findnext("na", "banana", 4)
5:6
----


=== O operador +∈+

O operador +∈+ (*+\in TAB+*) é um operador booleano que recebe um caractere e uma string e retorna +true+ se o caractere aparece na string:
((("∈", see="in")))((("operador", "Base", "in", see="in")))((("operador", "Base", "∈", see="in")))

[source,@julia-repl-test]
----
julia> 'a' ∈ "banana"    # 'a' em "banana"
true
----

Por exemplo, a seguinte função imprime todas as letras da palavra1 que também aparecem na palavra2:
(((emambos)))((("função", "definido pelo programador", "emambos", see="emambos")))

[source,@julia-setup chap08-2]
----
function emambos(palavra1, palavra2)
    for letra in palavra1
        if letra ∈ palavra2
            print(letra, " ")
        end
    end
end
----

Com variáveis de nomes bem escolhidos, o Julia as vezes lê como Inglês. Você poderia ler este loop, “para (cada) letra na (primeira) palavra, se (a) letra é um elemento da (segunda) palavra, imprima (a) letra”

Isso é o que você recebe se você compara +"maçãs"+ e +"laranjas"+:

[source,@julia-repl-test chap08-2]
----
julia> emambos("maçãs", "laranjas")
a s
----


=== Comparação de Strings

O operador relacional funciona em strings. Para ver se duas strings são iguais:
(((comparação de strings)))(((==)))

[source,@julia-setup chap08]
----
palavra = "Abacaxi"
if palavra == "banana"
    println("Tudo certo, bananas.")
end
----

Outras operações relacionais são utéis para colocar palavras em ordem alfabética:
(((ordem alfabética)))

[source,@julia-setup chap08]
----
if palavra < "banana"
    println("Sua palavra, $palavra, vem antes de banana.")
elseif palavra > "banana"
    println("Sua palavra, $palavra, vem depois de banana.")
else
    println("Tudo certo, bananas.")
end
----

Julia não lida letras maiúsculas e minúsculas do mesmo jeito que as pessoas lidam. Todas as letras maiúsculas vem antes de todas as letras minúsculas, então:

[source,@julia-eval chap08]
----
if palavra < "banana"
    println("Sua palavra, $palavra, vem antes de banana.")
elseif palavra > "banana"
    println("Sua palavra, $palavra, vem depois de banana.")
else
    println("Tudo certo, bananas.")
end
----

[TIP]
====
Um jeito comum de resolver este problema é convertendo strings para um formato padrão, como todas minúsculas, antes de efetuar a comparação.
====


[[deb08]]
=== Debugando

Quando você usa indíces para percorrer os valores em uma sequência, é difícil de obter o começo e o fim da travessia direito. Aqui está uma função que deveria comparar duas palavras e retornar +true+ se uma das palavras é o inverso da outra, mas ela contém dois erros:
(((debugando)))(((travessia)))(((éinversa)))((("função", "definido pelo programador", "éinversa", see="éinversa")))

[source,@julia-setup chap08]
----
function éinversa(palavra1, palavra2)
    if length(palavra1) != length(palavra2)
        return false
    end
    i = firstindex(palavra1)
    j = lastindex(palavra2)
    while j >= 0
        j = prevind(palavra2, j)
        if palavra1[i] != palavra2[j]
            return false
        end
        i = nextind(palavra1, i)
    end
    true
end
----

A primeira declaração +if+ verifica se as palavras são do mesmo tamanho. Se não, nós podemos retornar +false+ imediatamente. Caso contrário, para o resto da função, nós podemos assumir que as palavras são do mesmo tamanho. Isso é um exemplo do padrão guardião.

+i+ e +j+ são indíces: +i+ percorre a +palavra1+ de frente para trás, enquanto +j+ percorre a +palavra2+ de trás para frente. Se nós acharmos duas letras que não são iguais, nós podemos retornar +false+ imediatamente. Se nós passarmos pelo loop inteiro e todas as letras forem iguais, nós retornamos +true+.

A função +lastindex+ retorna o último indíce de bytes válido de uma string e +prevind+ o último indíce válido de um caractere.

Se nós testarmos essa função com as palavras "pots" e "stop", nós esperamos que o valor de retorno seja +true+, mas nós obtemos +false+:

[source,@julia-repl-test chap08]
----
julia> éinversa("pots", "stop")
false
----

Para debugar esse tipo de erro, o primeiro passo é imprimir os valores dos indíces:

[source,julia]
----
    while j >= 0
        j = prevind(palavra2, j)
        @show i j
        if palavra1[i] != palavra2[j]
----

[source,@julia-eval chap08]
----
function éinversa(palavra1, palavra2)
    if length(palavra1) != length(palavra2)
        return false
    end
    i = firstindex(palavra1)
    j = lastindex(palavra2)
    while j >= 0
        j = prevind(palavra2, j)
        @show i j
        if palavra1[i] != palavra2[j]
            return false
        end
        i = nextind(palavra1, i)
    end
    true
end;
----

Agora quando executamos novamente o programa, obtemos mais informação:

[source,@julia-repl-test chap08]
----
julia> éinversa("pots", "stop")
i = 1
j = 3
false
----

A primeira vez dentro do loop, o valor de +j+ é 3, que tem que ser 4. Isso pode ser consertado movendo +j = prevind(palavra2, j)+ para o final do loop +while+.

Se consertamos este erro e executamos novamente o programa, obtemos:

[source,@julia-eval chap08]
----
function éinversa(palavra1, palavra2)
    if length(palavra1) != length(palavra2)
        return false
    end
    i = firstindex(palavra1)
    j = lastindex(palavra2)
    while j >= 0
        @show i j
        if palavra1[i] != palavra2[j]
            return false
        end
        i = nextind(palavra1, i)
        j = prevind(palavra2, j)
    end
    true
end;
----

[source,@julia-repl-test chap08]
----
julia> éinversa("pots", "stop")
i = 1
j = 4
i = 2
j = 3
i = 3
j = 2
i = 4
j = 1
i = 5
j = 0
ERROR: BoundsError: attempt to access String
  at index [5]
----

Desta vez um +BoundsError+ foi gerado. O valor de +i+ é 5, que está fora do alcance para a string +"pots"+.
(((BoundsError)))((("erro", "Core", "BoundsError", see="BoundsError")))

===== Exercício 8-6

Execute o programa em papel, mudando os valores de +i+ e +j+ durante cada iteração. Encontre e conserte o segundo erro nesta função.


=== Glossário

sequência::
Uma coleção ordenada de valores no qual cada valor é identificado por um indíce inteiro.
(((sequência)))

Padrão ASCII::
Um padrão de codificação de caracteres para comunicação eletrônica que especifica 128 caracteres.
(((Padrão ASCII)))

Padrão Unicode::
Um padrão da indústria da computação para a codificação consistente, representação, e tratamento de texto expressado na maioria dos sistemas de escrita do mundo.
(((Padrão Unicode)))

indíce::
Um valor inteiro usado para selecionar um item em uma sequência, como um caractere em uma string. Em Julia indíces começam em 1.
(((indíce)))

Codificação UTF-8::
Uma codificação de comprimento variável de caractere capaz de codificar todas as 1112064 pontos de código usando um a quatro bytes de 8-bit.
(((Codificação UTF-8)))

travessia::
Iterar sobre os items de uma sequência, realizando operações similares em cada um deles.
(((travessia)))

fatia::
Uma parte de uma string especificado por um alcance de indíces.
(((fatia)))

string vazia::
Uma string sem caracteres e comprimento 0, representada por duas aspas.
(((string vazia)))

imutável::
A propriedade de uma sequência no qual seus items não podem ser mudados.
(((imutável)))

interpolação de strings::
O processo de avaliar uma string que contém um ou mais espaços reservados, produzindo um resultado no qual os espaços reservados são substituidos por seus valores correspondentes.
(((interpolação de strings)))

busca::
Um padrão de travessia que para quando acha o que está procurando.
(((busca)))

contador::
Uma variável usada para contar algo, geralmente inicializada para zero e em seguida incrementada.
(((contador)))


=== Exercícios

[[ex08-1]]
===== Exercício 8-7

Leia a documentação das funções string em https://docs.julialang.org/en/v1/manual/strings/. Você pode querer experimentar com algumas delas para garantir que você entende como elas funcionam. +strip+ e +replace+ são particulamente utéis.

A documentação usa uma sintaxe que pode ser confusa. Por exemplo, em +search(string::AbstractString, chars::Chars, [start::Integer])+, os colchetes indicam argumentos opcionais. Então +string+ e +chars+ são obrigatórios, mas +start+ é opcional.
(((busca)))((("função", "Base", "busca", see="busca")))

[[ex08-2]]
===== Exercício 8-8

Existe uma função embutida chamada +count+ que é similar à função em <<looping_and_counting>>. Leia a documentação desta função e a use para contar o número de +a+’s em "banana".
(((contar)))((("função","Base", "contar", see="contar")))

[[ex08-3]]
===== Exercício 8-9

Uma fatia de string pode receber um terceiro indíce. O primeiro especifica o começo, o terceiro o fim e o segundo o “tamanho do passo”; isto é, o número de espaços entre caracteres sucessivos. Um tamanho de passo de 2 significa que andamos de dois em dois; 3 significa de três em três, etc.
(((fatia)))

[source,@julia-repl-test]
----
julia> fruta = "banana"
"banana"
julia> fruta[1:2:6]
"bnn"
----

Um tamanho de passo -1 percorre a palavra ao contrário, então a fatia +[end:-1:1]+ gera uma string reversa.

Use esse idioma para escrever uma versão de uma linha de +ispalindrome+ do <<ex06-3>>.
(((ispalindrome)))

[[ex08-4]]
===== Exercício 8-10

As seguintes função são todas _planejadas_ para checar se a string contém alguma letra minúscula, mas pelo menos algumas delas estão erradas. Para cada função, descreva o que a função faz de fato (assumindo que o parâmetro é uma string).

[source,@julia-setup]
----
function qualquerminúscula1(s)
    for c in s
        if islowercase(c)
            return true
        else
            return false
        end
    end
end

function qualquerminúscula2(s)
    for c in s
        if islowercase('c')
            return "true"
        else
            return "false"
        end
    end
end

function qualquerminúscula3(s)
    for c in s
        flag = islowercase(c)
    end
    flag
end

function qualquerminúscula4(s)
    flag = false
    for c in s
        flag = flag || islowercase(c)
    end
    flag
end

function qualquerminúscula5(s)
    for c in s
        if !islowercase(c)
            return false
        end
    end
    true
end
----

[[ex08-5]]
===== Exercício 8-11
Uma cifra de César é uma forma fraca de criptografia que envolve “rotacionar” cada letra por um número fixo de lugares. Rotacionar uma letra significa deslocar ela através do alfabeto, retornando ao começo se necessário, então +’A’+ rotacionada por 3 é +’D’+ e +’Z’+ rotacionada por 1 é +’A’+.
(((cifra de César)))

Para rotacionar uma palavra, rotacione cada letra pelo mesmo valor. Por exemplo +"cheer"+ rotacionado por 7 é +"jolly"+ e +"melon"+ rotacionado por -10 é +"cubed"+. No filme _2001: Odisseia no espaço, o computador de bordo_ é chamado de HAL, que é IBM rotacionado por -1.

Escreva uma função chamada +rotacionapalavra+ que recebe uma string e um inteiro como parâmetros, e retorna uma nova string que contém as letras da string original rotacionada pela inteiro fornecido.
(((rotacionapalavra)))((("função","definido pelo programador", "rotacionapalavra", see="rotacionapalavra")))

[TIP]
====
Você pode querer usar as funções embutidas +Int+, que converte um caractere para um código numérico, e +Char+, que converte códigos numéricos para caracteres. Letras do alfabeto são codificadas em ordem alfabética, então por exemplo:
(((Int)))(((Char)))

[source,@julia-repl-test]
----
julia> Int('c') - Int('a')
2
----

Por quê +'c'+ é a terceira letra do alfabeto. Mas tome cuidado: os códigos numéricos para letras maiúsculas são diferentes.

[source,@julia-repl-test]
----
julia> Char(Int('A') + 32)
'a': ASCII/Unicode U+0061 (category Ll: letra, lowercase)
----
====

Piadas potencialmente ofensivas na internet são algumas vezes codificadas em ROT13, que é uma cifra de César com rotação 13. Se você não é facílmente ofendido, encontre e codifique algumas delas.
