[[chap19]]
== Extra: Sintaxe

Uma das nossas metas para este livro é ensinar o mínimo possível de Julia. Quando havia duas formas de fazer algo, escolhíamos uma e evitávamos mencionar a outra. Ou às vezes, propúnhamos a segunda forma como exercício.

Agora queremos retornar a algumas coisas boas que ficaram pra trás. O Julia oferece uma variadade de recursos que não são realmente necessários—você pode escrever um bom código sem eles—mas com eles pode-se escrever um código mais conciso, legível ou eficiente e, às vezes, todos os três.

Neste e no próximo capítulo, iremos discutir coisas dos capítulos anteriores que deixamos para trás:

* os suplementos de sintaxe
* as funções, os tipos e as macros diretamente disponíveis em +Base+
(((Base)))
* as funções, os tipos e as macros da Biblioteca Padrão
(((Biblioteca Padrão)))

=== Tuplas Nomeadas

Você pode nomear os componentes de uma tupla, criando uma tupla nomeada.

[source,@julia-repl-test]
----
julia> x = (a=1, b=1+1)
(a = 1, b = 2)
julia> x.a
1
----

Nas tuplas nomeadas, os campos podem ser acessados pelo nome usando a sintaxe do ponto +(x.a)+.
(((tupla nomeada)))(((sintaxe do ponto)))


=== Funções

Uma função no Julia pode ser definida por uma sintaxe compacta:

[source,@julia-repl-test]
----
julia> f(x,y) = x + y
f (generic function with 1 method)
----

[[anonymous_functions]]
==== Funções Anônimas

Podemos definir uma função sem especificar um nome:

[source,@julia-repl-test]
----
julia> x -> x^2 + 2x - 1
#1 (generic function with 1 method)
julia> function (x)
           x^2 + 2x - 1
       end
#3 (generic function with 1 method)
----

Estes são os exemplos de _funções anônimas_. E elas geralmente são usadas como argumentos para outras funções:
(((função anônima)))(((Plots)))((("módulo", "Plots", see="Plots")))(((plot)))((("função", "Plots", "plot", see="plot")))

[source,jlcon]
----
julia> using Plots

julia> plot(x -> x^2 + 2x - 1, 0, 10, xlabel="x", ylabel="y")

----

<<fig19-1>> mostra a saída do comando plot.

[[fig19-1]]
.Plot
image::images/fig191.svg[pdfwidth="10cm"]

==== Argumentos de Palavras-Chave

Argumentos de funções também podem ser nomeadas:

[source,@julia-repl-test]
----
julia> function meu_plot(x, y; style="solid", width=1, color="black")
           ###
       end
meu_plot (generic function with 1 method)
julia> meu_plot(0:10, 0:10, style="dotted", color="blue")

----

_Argumentos de palavras-chave_ em uma função são especificados depois de um ponto e vírgula na assinatura, apesar de poder ser chamado com uma vírgula.
(((;)))(((argumentos de palavra-chave)))

==== Fechamentos

Um _fechamento_ é uma técnica que permite uma função capturar uma variável definida fora do escopo da chamada da função.

[source,@julia-repl-test]
----
julia> foo(x) = ()->x
foo (generic function with 1 method)

julia> bar = foo(1)
#1 (generic function with 1 method)

julia> bar()
1
----

Nesse exemplo, a função +foo+ retorna uma função anônima que possui acesso ao argumento +x+ da função +foo+. A variável +bar+ aponta para a função anônima e retorna o valor do argumento de +foo+.


=== Blocos

Um _bloco_ é uma forma de agrupar diversos comandos. Um bloco começa com a palavra-chave +begin+ e termina com +end+.
(((begin)))((("palavra-chave", "begin", see="begin")))(((end)))(((bloco)))

No <<chap04>>, a macro +@svg+ foi introduzida:

[source,julia]
----
🐢 = Turtle()
@svg begin
    forward(🐢, 100)
    turn(🐢, -90)
    forward(🐢, 100)
end
----

Neste exemplo, a macro +@svg+ possui um argumento único, i.e. um bloco que está agrupando 3 chamadas de função.

==== Blocos +let+

Um bloco +let+ é útil para criar novas ligações, i.e. locais que podem se referir a valores.

[source,@julia-repl-test]
----
julia> x, y, z = -1, -1, -1;

julia> let x = 1, z
           @show x y z;
       end
x = 1
y = -1
ERROR: UndefVarError: z not defined
julia> @show x y z;
x = -1
y = -1
z = -1
----

Nesse exemplo, a primeira macro +@show+ mostra o +x+ local, a global +y+ e a local indefinida +z+. As variáveis globais são intocáveis.


==== Blocos +do+

Em <<reading_and_writing>>, tivemos que fechar o arquivo após o término da escrita. Isso pode ser feito automaticamente usando um _bloco do_:
(((do)))((("palavra-chave", "do", see="do")))

[source,@julia-repl-test chap19]
----
julia> dado = "O meu nome é Severino, \nnão tenho outro de pia.\n"
"O meu nome é Severino, \nnão tenho outro de pia.\n"
julia> open("output.txt", "w") do fout
           write(fout, dado)
       end
48
----

Nesse exemplo, +fout+ é um fluxo de arquivo usado para a saída.

Essa funcionalidade é equivalente a

[source,@julia-repl-test chap19]
----
julia> f = fout -> begin
           write(fout, dado)
       end
#3 (generic function with 1 method)
julia> open(f, "output.txt", "w")
48
----

A função anônima é usada como o primeiro argumento da função +open+:
(((open)))

[source,julia]
----
function open(f::Function, args...)
    io = open(args...)
    try
        f(io)
    finally
        close(io)
    end
end
----

Um bloco +do+ pode “capturar” as variáveis dos seus escopos anexos. Por exemplo, a variável +dado+ em +open pass:[...] do+ no exemplo acima é capturada de outro escopo.


=== Controle de Fluxo

==== Operador Ternário

O _operador ternário_ +?:+ é uma alternativa para uma declaração +if-else+ usada quando você precisa fazer uma escolha entre valores de expressão única.
(((?:)))((("operador", "Base", "?:", see="?:")))((("operador ternário", see="?:")))

[source,@julia-repl-test]
----
julia> a = 150
150
julia> a % 2 == 0 ? println("par") : println("ímpar")
par
----

A expressão antes de +?+ é uma condição. Se a condição for +true+, a expressão antes de +:+ é avaliada, caso contrário, a expressão depois de +:+ é avaliada.

==== Avaliação de Curto-Circuíto

Os operadores +&&+ e +||+ fazem uma _avaliação de curto-circuito_: o próximo argumento só é avaliado quando é necessário determinar o valor final.
(((&&)))(((||)))(((avaliação de curto-circuito)))

Por exemplo, uma rotina recursiva do fatorial pode ser definida da seguinte maneira:
(((fat)))

[source,@julia-setup]
----
function fat(n::Integer)
    n >= 0 || error("n deve ser inteiro não negativo")
    n == 0 && return 1
    n * fat(n-1)
end
----

==== Tarefas (também conhecida como Corrotina)

Uma _tarefa_ é uma estrutura de controle que pode passar pelo controle cooperativamente sem retornar. Em Julia, uma tarefa pode ser implementada como uma função tendo como o primeiro argumento um objeto de canal (+Channel+). Um canal é usado para passar valores de uma função para quem a chamou.

A sequência de Fibonnaci pode ser gerada por uma tarefa.
(((tarefa)))(((Channel)))((("tipo", "Base", "Channel", see="Channel")))(((put!)))((("função", "Base", "put!", see="put!")))

[source,@julia-setup chap19]
----
function fib(c::Channel)
    a = 0
    b = 1
    put!(c, a)
    while true
        put!(c, b)
        (a, b) = (b, a+b)
    end
end
----

+put+ armazena os valores em um objeto de canal e +take!+ lê os valores dele:
(((take!)))((("função", "Base", "take!", see="take!")))

[source,@julia-repl-test chap19]
----
julia> fib_gen = Channel(fib);

julia> take!(fib_gen)
0
julia> take!(fib_gen)
1
julia> take!(fib_gen)
1
julia> take!(fib_gen)
2
julia> take!(fib_gen)
3
----

O construtor +Channel+ cria a tarefa. A função +fib+ é suspendida aṕos cada chamada para +put!+ e retorna depois de +take!+. Por questões de performance, diversos valores da sequência são armazenados temporariamente no objeto de canal durante um ciclo de retomada/suspensão.

Um objeto de canal também pode ser usado como um iterador:

[source,@julia-repl-test chap19]
----
julia> for val in Channel(fib)
           print(val, " ")
           val > 20 && break
       end
0 1 1 2 3 5 8 13 21
----


=== Tipos

==== Tipos Primitivos

Um tipo concreto que consiste em bits simples e antigos é chamado de _tipo primitivo_. Ao contrário da maioria das linguagens, no Julia você pode declarar os seus próprios tipos primitivos. Os tipos primitivos padrões são definidos da mesma maneira:
(((tipo primitivo)))((("palavra-chave", "tipo primitivo", see="tipo primitivo")))

[source,julia]
----
primitive type Float64 <: AbstractFloat 64 end
primitive type Bool <: Integer 8 end
primitive type Char <: AbstractChar 32 end
primitive type Int64 <: Signed 64 end
----

O número nos comandos especificam quantos bits são necessários.

O exemplo a seguir cria um tipo primitivo +Byte+ e um construtor:
(((Byte)))((("tipo", "definido pelo programador", "Byte", see="Byte")))

[source,@julia-repl-test]
----
julia> primitive type Byte 8 end

julia> Byte(val::UInt8) = reinterpret(Byte, val)
Byte
julia> b = Byte(0x01)
Byte(0x01)
----

A função +reinterpret+ é usada para armazenar os bits de um inteiro não assinado com 8 bits (+UInt8+) no byte.
(((reinterpret)))((("função", "Base", "reinterpret", see="reinterpret")))(((UInt8)))((("tipo", "Base", "UInt8", see="UInt8")))

==== Tipos Paramétricos

O tipo de sistema do Julia é _paramétrico_, significando que os tipos podem possuir parâmetros.

Parâmetros de tipo são introduzidos depois do nome do tipo, cercado por chaves:
(((chaves)))

[source,@julia-setup chap19]
----
struct Ponto{T<:Real}
    x::T
    y::T
end
----

Isso define um novo tipo paramétrico, +Ponto{T<:Real}+, segurando duas "coordenadas" do tipo +T+, da qual pode ser de qualquer tipo desde que tenha +Real+ como supertipo.

[source,@julia-repl-test chap19]
----
julia> Ponto(0.0, 0.0)
Ponto{Float64}(0.0, 0.0)
----

Além dos tipos compostos, tipos abstratos e tipos primitivos também podem ter um parâmetro de tipo.

[TIP]
====
Ter tipos concretos nos campos da struct é absolutamente recomendado por motivos de desempenho, portanto essa é uma boa maneira de tornar +Ponto+ rápido e flexível.
====

==== União de Tipo

Uma _união de tipo_ é um tipo paramétrico abstrato que pode atuar como qualquer um dos tipos do seu argumento:
(((união de tipo)))(((Union)))((("tipo", "Base", "Union", see="Union")))

[source,@julia-repl-test]
----
julia> IntOrString = Union{Int64, String}
Union{Int64, String}
julia> 150 :: IntOrString
150
julia> "Julia" :: IntOrString
"Julia"
----

Uma união de tipo é na maioria das linguagens de computador uma construção interna para pensar sobre os tipos. O Julia, no entanto, expõe esse recurso aos seus usuários porque um código eficiente pode ser gerado quando a união de tipo possui um pequeno número de tipos. Esse recurso oferece ao programador do Julia uma tremenda flexibilidade para controlar o despacho.

=== Métodos

==== Métodos Paramétricos

As definições de método também podem ter parâmetros de tipo que qualificam sua assinatura:
(((assinatura)))

[source,@julia-repl-test chap19]
----
julia> é_ponto_int(p::Ponto{T}) where {T} = (T === Int64)
é_ponto_int (generic function with 1 method)
julia> p = Ponto(1, 2)
Ponto{Int64}(1, 2)
julia> é_ponto_intt(p)
true
----

==== Objetos Semelhantes a Funções

Qualquer objeto arbitrário de Julia pode ser “chamado”. Tais objetos “chamáveis” às vezes são denominados  _funtores_.
(((funtor)))

[source,@julia-setup chap19]
----
struct Polinômio{R}
    coeff::Vector{R}
end

function (p::Polinômio)(x)
    val = p.coeff[end]
    for coeff in p.coeff[end-1:-1:1]
        val = val * x + coeff
    end
    val
end
----

Para calcular o polinômio, basta chamá-lo:

[source,@julia-repl-test chap19]
----
julia> p = Polinômio([1,10,100])
Polinômio{Int64}([1, 10, 100])
julia> p(3)
931
----

=== Construtores

Tipos paramétricos podem ser explicitamente ou implicitamente construídos:

[source,@julia-repl-test chap19]
----
julia> Ponto(1,2)         # implicit T
Ponto{Int64}(1, 2)
julia> Ponto{Int64}(1, 2) # explicit T
Ponto{Int64}(1, 2)
julia> Ponto(1,2.5)       # implicit T
ERROR: MethodError: no method matching Ponto(::Int64, ::Float64)
----

Construtores internos e externos padrões são gerados para cada +T+:
(((construtor)))

[source,julia]
----
struct Ponto{T<:Real}
    x::T
    y::T
    Ponto{T}(x,y) where {T<:Real} = new(x,y)
end

Ponto(x::T, y::T) where {T<:Real} = Ponto{T}(x,y);
----

e ambos +x+ e +y+ devem ser do mesmo tipo.

Quando +x+ e +y+ possuem tipos diferentes, o subsequente construtor externo pode ser definido como:

[source,@julia-setup chap19]
----
Ponto(x::Real, y::Real) = Ponto(promote(x,y)...);
----

A função +promote+ é detalhada em <<promotion>>.
(((promote)))((("função", "Base", "promote", see="promote")))

=== Conversão e Promoção

O Julia tem um sistema para promover argumentos para um tipo comum. Isso não é feito automaticamente, mas pode ser facilmente realizado.

==== Conversão

Um valor pode ser convertido de um tipo para o outro:
(((conversão)))(((convert)))((("função", "Base", "convert", see="convert")))

[source,@julia-repl-test]
----
julia> x = 12
12
julia> typeof(x)
Int64
julia> convert(UInt8, x)
0x0c
julia> typeof(ans)
UInt8
----

Podemos adicionar os nossos próprios métodos +convert+:
[source,@julia-repl-test chap19]
----
julia> Base.convert(::Type{Ponto{T}}, x::Array{T, 1}) where {T<:Real} = Ponto(x...)

julia> convert(Ponto{Int64}, [1, 2])
Ponto{Int64}(1, 2)
----

[[promotion]]
==== Promoção

_Promoção_ é a conversão de valores dos tipos mistos para um único tipo comum:
(((promoção)))(((promote)))

[source,@julia-repl-test]
----
julia> promote(1, 2.5, 3)
(1.0, 2.5, 3.0)
----

Em geral, os métodos para a função +promote+ não são diretamente definidos, mas a função auxiliar +promote_rule+ é usada para especificar as regras da promoção:
(((promote_rule)))((("função", "Base", "promote_rule", see="promote_rule")))

[source,julia]
----
promote_rule(::Type{Float64}, ::Type{Int32}) = Float64
----

=== Metaprogramação

O código Julia pode ser representado como uma estrutura de dados da própria linguagem. Isso permite que um programa transforme e gere o seu próprio código.

==== Expressões

Todo programa do Julia começa como uma string:

[source,@julia-repl-test chap19]
----
julia> prog = "1 + 2"
"1 + 2"
----

A próxima etapa é analisar cada string em um objeto chamado _expression_, representado pelo tipo +Expr+ do Julia:
(((expression)))(((Expr)))((("tipo", "Base", "Expr", see="Expr")))(((parse)))((("função", "Meta", "parse", see="parse")))

[source,@julia-repl-test chap19]
----
julia> ex = Meta.parse(prog)
:(1 + 2)
julia> typeof(ex)
Expr
julia> dump(ex)
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol +
    2: Int64 1
    3: Int64 2
----

A função +dump+ detalha os objetos expr.
(((dump)))

Expressões podem ser diretamente construídas prefixando +:+ entre parênteses ou usando uma citação em bloco
(((:)))(((quote)))((("palavra-chave", "quote", see="quote")))

[source,@julia-repl-test chap19]
----
julia> ex = quote
           1 + 2
       end;
----

==== +eval+

O Julia pode avaliar um objeto de expressão usando +eval+:
(((eval)))((("função", "Core", "eval", see="eval")))

[source,@julia-eval chap19]
----
import Base.eval
----

[source,@julia-repl-test chap19]
----
julia> eval(ex)
3
----

Cada módulo possui sua própria função +eval+ que avalia as expressões em seu escopo.

[WARNING]
====
Quando você está usando muitas chamadas para a função +eval+, geralmente isso significa que algo está errado. A função +eval+ é considerada do “mal”.
====

==== Macros

Macros podem incluir o código gerado em um programa. Uma _macro_ mapeia uma tupla de objetos +Expr+ diretamente para uma expressão compilada:
(((macro)))

Aqui está uma macro simples:
(((@containervariável)))((("macro", "definido pelo programador", "@containervariável", see="@containervariável")))

[source,@julia-setup chap19]
----
macro containervariável(container, elemento)
    return esc(:($(Symbol(container,elemento)) = $container[$elemento]))
end
----

As macros são chamadas ao colocar o prefixo +@+ (sinal de arroba) em seus nomes. A macro chamada +@containervariável letras 1+ é substituída por:
(((@)))

[source,julia]
----
:(letras1 = letras[1])
----

+@macroexpand @containervariável letras 1+ retorna essa expressão que é extremamente útil para a depuração.
(((@macroexpand)))((("macro", "Base", "@macroexpand", see="@macroexpand")))

Este exemplo ilustra como uma macro pode acessar o nome dos seus argumentos, algo que uma função não pode fazer. O comando return precisa ser “escapado” com +esc+, pois precisa ser resolvido no ambiente da chamada da macro.
(((esc)))((("função", "Base", "esc", see="esc")))

[NOTE]
====
Por que macros?

As macros geram e incluem fragmentos de código personalizado durante o tempo de análise, portanto, _antes_ da execução do programa completo.
====

==== Funções Geradas

A macro +@generated+ cria código especializado para os métodos, dependendo dos tipos dos argumentos:
(((funções geradas)))(((@generated)))((("macro", "Base", "@generated", see="@generated")))

[source,@julia-setup chap19]
----
@generated function quadrado(x)
    println(x)
    :(x * x)
end
----

O corpo retorna uma expressão entre aspas como uma macro.

Para quem chama, a _função gerada_ se comporta como uma função regular:

[source,@julia-repl-test chap19]
----
julia> x = quadrado(2); # nota: a saída é da declaração println() no corpo
Int64
julia> x              # agora imprimimos x
4
julia> y = quadrado("spam");
String
julia> y
"spamspam"
----

=== Valores Ausentes

_Valores ausentes_ podem ser representados através do objeto +missing+, que é a instância singleton do tipo +Missing+.
(((valores ausentes)))(((missing)))(((Missing)))((("tipo", "Base", "Missing", see="Missing")))

As listas podem conter valores ausentes:

[source,@julia-repl-test chap19]
----
julia> a = [1, missing]
2-element Array{Union{Missing, Int64},1}:
 1
  missing
----

O tipo de elemento dessa lista é +Union{Missing, T}+, sendo +T+ o tipo de valores não ausentes.

As funções de redução retornam +missing+ quando chamadas nas listas que contêm valores ausentes

[source,@julia-repl-test chap19]
----
julia> sum(a)
missing
----

Nessa situação, use a função +skipmissing+ para ignorar os valores ausentes:
(((skipmissing)))((("função", "Base", "skipmissing", see="skipmissing")))

[source,@julia-repl-test chap19]
----
julia> sum(skipmissing([1, missing]))
1
----


=== Chamando Códigos em C e Fortran

Muitos códigos estão escritos em C ou Fortran. Reutilizar o código testado geralmente é melhor do que escrever sua própria versão de um algoritmo. Julia pode chamar diretamente as bibliotecas existentes em C ou Fortran usando a sintaxe +ccall+.
(((ccall)))((("função", "Base", "ccall", see="ccall")))

Em <<databases>>, introduzimos uma interface Julia para a biblioteca GDBM de funções de banco de dados. A biblioteca está escrita em C. Para fechar o banco de dados, uma chamada de função para +close(db)+ teve que ser feita:

[source,julia]
----
Base.close(dbm::DBM) = gdbm_close(dbm.handle)

function gdbm_close(handle::Ptr{Cvoid})
    ccall((:gdbm_close, "libgdbm"), Cvoid, (Ptr{Cvoid},), handle)
end
----

Um objeto dbm possui um campo +handle+ do tipo +Ptr{Cvoid}+. Este campo guarda um ponteiro C que se refere ao banco de dados. Para fechar o banco de dados, a função C +gdbm_close+ deve ser chamada tendo como único argumento o ponteiro C apontando para o banco de dados e sem valor de retorno. O Julia faz isso diretamente com a função +ccall+ tendo como argumentos:
(((Ptr)))((("tipo", "Base", "Ptr", see="Ptr")))

* uma tupla que consiste em um símbolo que contém o nome da função que queremos chamar: +:gdbm_close+ e a biblioteca compartilhada especificada como uma string: +"libgdm"+,

* o tipo de retorno: +Cvoid+,

* uma tupla com os tipos de argumentos: +(Ptr{Cvoid},)+ e

* os valores do argumento: +handle+.

O mapeamento completo da biblioteca GDBM pode ser encontrado como um exemplo no repositório do JuliaIntroBR.

=== Glossário

fechamento::
Função que captura as variáveis do seu escopo definido.
(((fechamento)))

bloco let::
Bloco que aloca novas ligações de variáveis.
(((bloco let)))

função anônima::
Função definida sem ter um nome.
(((função anônima)))

tupla nomeada::
Tupla com componentes nomeados.
(((tupla nomeada)))

argumentos de palavra-chave::
Argumentos identificados pelo nome e não só pela posição.
(((argumentos de palavra-chave)))

bloco do::
Construção de sintaxe usada para definir e chamar uma função anônima que se parece com um bloco de código normal.
(((bloco do)))

operador ternário::
Operador de fluxo de controle que usa três operandos para especificar uma condição, uma expressão a ser executada quando a condição produz +true+ e uma expressão a ser executada quando a condição produz +false+.
(((operador ternário)))

avaliação de curto-circuíto::
Avaliação de um operador booleano na qual o segundo argumento é executado ou avaliado apenas se o primeiro argumento não for suficiente para determinar o valor da expressão.
(((avaliação de curto-circuíto)))

tarefa (também conhecida como Corrotina)::
Recurso de fluxo de controle que permite a suspensão e a retomada dos cálculos de maneira flexível.
(((tarefa)))

tipo primitivo::
Tipo concreto cujos dados consistem em bits simples e antigos.
(((tipo primitivo)))

união de tipo::
Tipo que inclui como objetos todas as instâncias de qualquer um dos seus parâmetros de tipo.
(((união de tipo)))

tipo paramétrico::
Tipo que é parametrizado.
(((tipo paramétrico)))

funtor::
Objeto com um método associado, para que ele possa ser chamado.
(((funtor)))

conversão::
A conversão permite converter um valor de um tipo para outro.
(((conversão)))

promoção::
Conversão de valores de tipos mistos em um único tipo comum.
(((promoção)))

expressão::
Tipo do Julia que contém uma construção de linguagem.
(((expressão)))

macro::
Forma de incluir o código gerado no final do corpo de um programa.
(((macro)))

funções geradas::
Funções capazes de gerar código especializado, dependendo dos tipos dos argumentos.
(((funções geradas)))

valores ausentes::
Instâncias que representam informações sem valor.
(((valores ausentes)))
