[[chap19]]
== Extra: Sintaxe

Uma das metas deste livro é ensinar o mínimo possível de Julia. Quando havia duas formas de fazer algo, escolhiamos uma e evitavamos mencionar a outra. Ou às vezes, utilizamos a segunda forma como exercício.

Agora queremos retornar a algumas coisas boas que ficaram para traz. O Julia oferece uma variadade de recursos que não são realmente necessários – você pode escrever um bom código sem eles – mas com eles é possível escrever um código mais conciso, legível ou eficiente e, às vezes, todos os três.

Neste capítulo e no próximo, iremos discutir coisas que deixamos para trás nos capótulos anteriores:

* suplementos de sintaxe
* funções, tipos e macros diretamente disponíveis em +Base+
(((Base)))
* funções, tipos e macros da Biblioteca Padrão
(((Biblioteca Padrão)))

=== Tuplas Nomeadas

Podemos nomear os componentes de uma tupla, criando uma tupla nomeada.

[source,@julia-repl-test]
----
julia> x = (a=1, b=1+1)
(a = 1, b = 2)
julia> x.a
1
----

Com tuplas nomeadas, os campos podem ser acessados por nome usando a sintaxe do ponto +(x.a)+.
(((tuplas nomeadas)))(((sintaxe do ponto)))


=== Funções

Uma função no Julia pode ser definida através de uma sintaxe compacta:

[source,@julia-repl-test]
----
julia> f(x,y) = x + y
f (generic function with 1 method)
----

[[anonymous_functions]]
==== Funções Anônimas

Podemos definir uma função sem especificar um nome:

[source,@julia-repl-test]
----
julia> x -> x^2 + 2x - 1
#1 (generic function with 1 method)
julia> function (x)
           x^2 + 2x - 1
       end
#3 (generic function with 1 method)
----

Esses são exemplos de _funções anônimas_. Funções anonimas geralmente são usadas como argumentos para outras funções:
(((funções anônimas)))(((Plots)))((("módulo", "Plots", see="Plots")))(((plot)))((("função", "Plots", "plot", see="plot")))

[source,jlcon]
----
julia> using Plots

julia> plot(x -> x^2 + 2x - 1, 0, 10, xlabel="x", ylabel="y")

----

<<fig19-1>> mostra a saída do comando plot.

[[fig19-1]]
.Plot
image::images/fig191.svg[pdfwidth="10cm"]

==== Argumentos de Palavras-Chave

Argumentos de funções também podem ser nomeadas:

[source,@julia-repl-test]
----
julia> function myplot(x, y; style="solid", width=1, color="black")
           ###
       end
myplot (generic function with 1 method)
julia> myplot(0:10, 0:10, style="dotted", color="blue")

----

_Argumentos de palavras-chave_ em uma função são especificadas depois de um ponto e vírgula na assinatura, mas pode ser chamado com uma vírgula.
(((;)))(((argumentos de palavra-chave)))

=== Fechamentos

Um _fechamento_ é a técnica que permite uma função capturar uma variável definida fora do escopo de chamada de função.

[source,@julia-repl-test]
----
julia> foo(x) = ()->x
foo (generic function with 1 method)

julia> bar = foo(1)
#1 (generic function with 1 method)

julia> bar()
1
----

Nesse exemplo, a função +foo+ retorna uma função anônima que possui acesso ao argumento +x+ da função +foo+. +bar+ aponta para a função anônima e retorna o valor do argumento de +foo+.


=== Blocos

Um _bloco_ é uma forma de agrupar diversos comandos. Um bloco começa com a palavra chave +begin+ e finaliza com +end+.
(((begin)))((("palavra-chave", "begin", see="begin")))(((end)))(((bloco)))

No <<chap04>> a macro +@svg+ foi introduzida:

[source,julia]
----
🐢 = Turtle()
@svg begin
    forward(🐢, 100)
    turn(🐢, -90)
    forward(🐢, 100)
end
----

Neste exemplo, a macro +@svg+ possui um argumento único, i.e. um bloco agrupando 3 chamadas de funções.

==== Blocos +let+

Um bloco +let+ é últil para criar novas ligações, i.e. locais que podem se referir a valores.

[source,@julia-repl-test]
----
julia> x, y, z = -1, -1, -1;

julia> let x = 1, z
           @show x y z;
       end
x = 1
y = -1
ERROR: UndefVarError: z not defined
julia> @show x y z;
x = -1
y = -1
z = -1
----

No exemplo, a primeira macro +@show+, mostra o +x+ local, a global +y+ e a local indefinida +z+. As variáveis globais são intocáveis.


==== Blocos +do+

Em <<reading_and_writing>> tivemos que fechar o arquivo após o término da gravação. Isso pode ser feito automaticamente usando um _bloco do_:
(((do)))((("palavra-chave", "do", see="do")))

[source,@julia-repl-test chap19]
----
julia> dado = "Aqui está a acácia,\no emblema de nossa terra.\n"
"Aqui está a acácia,\no emblema de nossa terra.\n"
julia> open("output.txt", "w") do fout
           write(fout, dado)
       end
48
----

Nesse exemplo, +fout+ é um fluxo de arquivo usado para saída.

Essa funcionalidade é equivalente a

[source,@julia-repl-test chap19]
----
julia> f = fout -> begin
           write(fout, dado)
       end
#3 (generic function with 1 method)
julia> open(f, "output.txt", "w")
48
----

A função anônima é usada como o primeiro argumento da função +open+:
(((open)))

[source,julia]
----
function open(f::Function, args...)
    io = open(args...)
    try
        f(io)
    finally
        close(io)
    end
end
----

Um bloco +do+ pode "caputar" variáveis de seus escopos anexos. Por exemplo, a variável +dado+ no exemplo acima de +open pass:[...] do+ é caputado de outro escopo.


=== Controle de Fluxo

==== Operador Ternário

O _operador ternário_, +?:+, é uma alternativa para uma declaração +if-else+ usada quando você precisa fazer uma escolha entre valores de expressão única.
(((?:)))((("operator", "Base", "?:", see="?:")))((("operador ternário", see="?:")))

[source,@julia-repl-test]
----
julia> a = 150
150
julia> a % 2 == 0 ? println("even") : println("odd")
even
----

A expressão antes de +?+ é uma expressão de condição. Se a condição for +true+, a expressão antes de +:+ é avaliada, caso contrário, a expressão depois de +:+ é avaliada.

==== Avaliação de Curto-Circuíto

Os operadores +&&+ e +||+ fazem uma _avaliação de curto-circuito_: O próximo argumento só é avaliado quando é necessário para determinar o valor final.
(((&&)))(((||)))(((avaliação de curto-circuito)))

Por exemplo, uma rotira de fatorial por recursão pode ser definida da seguinte maneira:
(((fat)))

[source,@julia-setup]
----
function fat(n::Integer)
    n >= 0 || error("n deve ser inteiro positivo")
    n == 0 && return 1
    n * fat(n-1)
end
----

==== Tarefas (também conhecido Corrotina)

Uma _tarefa_ é uma estrutura de controle que pode passar pelo controle cooperativo sem retornar. Em Julia, uma tarefa pode ser implementada como uma função tendo como primeiro argumento um objeto de canal (+Channel+). Um canal é usado para passar valores de uma função ao chamador.

A sequência de Fibonnaci pode ser gerada usando uma tarefa.
(((tarefa)))(((Canal)))((("tipo", "Base", "Channel", see="Channel")))(((put!)))((("função", "Base", "put!", see="put!")))

[source,@julia-setup chap19]
----
function fib(c::Channel)
    a = 0
    b = 1
    put!(c, a)
    while true
        put!(c, b)
        (a, b) = (b, a+b)
    end
end
----

+put+ armazena valores em um objeto de canal e +take!+ lê valores de:
(((take!)))((("função", "Base", "take!", see="take!")))

[source,@julia-repl-test chap19]
----
julia> fib_gen = Channel(fib);

julia> take!(fib_gen)
0
julia> take!(fib_gen)
1
julia> take!(fib_gen)
1
julia> take!(fib_gen)
2
julia> take!(fib_gen)
3
----

O construtor +Channel+ cria uma tarefa. A função +fib+ é suspendida depois de cada chamada para +put!+ e retorna depois de +take!+. Por questões de performance, muitos valores das sequências são armazenadas em buffer no objeto de canal durante um ciclo de retomada/suspensão.

Um objeto de canal também pode ser usado como um iterador:

[source,@julia-repl-test chap19]
----
julia> for val in Channel(fib)
           print(val, " ")
           val > 20 && break
       end
0 1 1 2 3 5 8 13 21
----


=== Tipos

==== Tipos Primitivos

Um tipo concreto que consiste em bits antigos simples é chamado de _tipo primitivo_. Ao contrário da maioria das linguagens, com Julia, você pode declarar seus próprios tipos primitivos. Os tipos primitivos padrão são definidos da mesma maneira:
(((tipo primitivo)))((("palavra-chave", "tipo primitivo", see="tipo primitivo")))

[source,julia]
----
primitive type Float64 <: AbstractFloat 64 end
primitive type Bool <: Integer 8 end
primitive type Char <: AbstractChar 32 end
primitive type Int64 <: Signed 64 end
----

O número nos comandos especificam quantos bits são necessários.

O exemplo à seguir cria um tipo primitivo +Byte+ e um construtor:
(((Byte)))((("tipo", "definido pelo programador", "Byte", see="Byte")))

[source,@julia-repl-test]
----
julia> primitive type Byte 8 end

julia> Byte(val::UInt8) = reinterpret(Byte, val)
Byte
julia> b = Byte(0x01)
Byte(0x01)
----

A função +reinterpret+ é usada para armazenar os bits de um inteiro não assinado com 8 bits (+UInt8+) no bit.
(((reinterpret)))((("função", "Base", "reinterpret", see="reinterpret")))(((UInt8)))((("Tipo", "Base", "UInt8", see="UInt8")))

==== Tipos Paramétricos

O tipo de sistema do Julia é _paramétrico_, o que significa que os tipos podem possuir parâmetros.

Tipos de Parâmetros são introduzidos depois do nome do tipo, cercado por chaves:
(((chaves)))

[source,@julia-setup chap19]
----
struct Point{T<:Real}
    x::T
    y::T
end
----

Isso define um novo tipo paramétrico, +Point{T<:Real}+, segurando duas "coordenadas" de tipo +T+, da qual pode ser qualquer tipo contendo +Real+ como supertipo.

[source,@julia-repl-test chap19]
----
julia> Point(0.0, 0.0)
Point{Float64}(0.0, 0.0)
----

Além dos tipos compostos, tipos abstratos e tipos primitivos também podem ter um parâmetro de tipo.

[TIP]
====
Ter tipos concretos para campos de estrutura é absolutamente recomendado por motivos de desempenho, portanto, é uma boa maneira de tornar o +Point+ rápido e flexível.
====

==== Tipo de União

Um _tipo de união_ é um tipo paramétrico abstrato que pode atuar como qualquer um dos seus tipos de argumento:
(((tipo de união)))(((Union)))((("tipo", "Base", "Union", see="Union")))

[source,@julia-repl-test]
----
julia> IntOrString = Union{Int64, String}
Union{Int64, String}
julia> 150 :: IntOrString
150
julia> "Julia" :: IntOrString
"Julia"
----

Uma união de tipos é na maioria das linguagens de computador uma construção interna para raciocinar sobre tipos. Julia, no entanto, expõe esse recurso a seus usuários porque um código eficiente pode ser gerado quando a união de tipos possui um pequeno número de tipos. Esse recurso oferece ao programador Julia uma tremenda flexibilidade para controlar o envio.

=== Métodos

==== Métodos Paramétricos

As definições de método também podem ter parâmetros de tipo que qualificam sua assinatura:
(((assinatura)))

[source,@julia-repl-test chap19]
----
julia> isintpoint(p::Point{T}) where {T} = (T === Int64)
isintpoint (generic function with 1 method)
julia> p = Point(1, 2)
Point{Int64}(1, 2)
julia> isintpoint(p)
true
----

==== Objetos Semelhantes a Funções

Qualquer objeto arbitrário de Julia pode ser "chamado". Tais objetos "chamáveis" às vezes são chamados de "funtores".
(((funtor)))

[source,@julia-setup chap19]
----
struct Polynomial{R}
    coeff::Vector{R}
end

function (p::Polynomial)(x)
    val = p.coeff[end]
    for coeff in p.coeff[end-1:-1:1]
        val = val * x + coeff
    end
    val
end
----

Para calcular o polinômio, basta chamá-lo:

[source,@julia-repl-test chap19]
----
julia> p = Polynomial([1,10,100])
Polynomial{Int64}([1, 10, 100])
julia> p(3)
931
----

=== Construtores

Tipos paramétricos podem ser explicitamente ou implicitamente construídos:

[source,@julia-repl-test chap19]
----
julia> Point(1,2)         # implicit T
Point{Int64}(1, 2)
julia> Point{Int64}(1, 2) # explicit T
Point{Int64}(1, 2)
julia> Point(1,2.5)       # implicit T
ERROR: MethodError: no method matching Point(::Int64, ::Float64)
----

Construtores internos e externos padrão são gerados para cada +T+:
(((construtor)))

[source,julia]
----
struct Point{T<:Real}
    x::T
    y::T
    Point{T}(x,y) where {T<:Real} = new(x,y)
end

Point(x::T, y::T) where {T<:Real} = Point{T}(x,y);
----

e ambos +x+ e +y+ devem ser do mesmo tipo.

Quando +x+ e +y+ possuem tipos diferentes, o seguinte construtor externo pode ser definido:

[source,@julia-setup chap19]
----
Point(x::Real, y::Real) = Point(promote(x,y)...);
----

A função +promote+ é detalhada em <<promotion>>.
(((promote)))((("função", "Base", "promote", see="promote")))

=== Conversão e Promoção

O Julia tem um sistema para promover argumentos para um tipo comum. Isso não é feito automaticamente, mas pode ser facilmente estendido.

==== Conversão

Um valor pode ser convertido de um tipo para outro:
(((conversão)))(((convert)))((("função", "Base", "convert", see="convert")))

[source,@julia-repl-test]
----
julia> x = 12
12
julia> typeof(x)
Int64
julia> convert(UInt8, x)
0x0c
julia> typeof(ans)
UInt8
----

Podemos adicionar nossos próprios métodos +convert+:
[source,@julia-repl-test chap19]
----
julia> Base.convert(::Type{Point{T}}, x::Array{T, 1}) where {T<:Real} = Point(x...)

julia> convert(Point{Int64}, [1, 2])
Point{Int64}(1, 2)
----

[[promotion]]
==== Promoção

_Promoção_ é a conversão de valores de tipos mistos para um único tipo comum:
(((promoção)))(((promote)))

[source,@julia-repl-test]
----
julia> promote(1, 2.5, 3)
(1.0, 2.5, 3.0)
----

Os métodos para a função +promote+ normalmente não são definidos diretamente, mas a função auxiliar +promover_rule+ é usada para especificar as regras da promoção:
(((promote_rule)))((("function", "Base", "promote_rule", see="promote_rule")))

[source,julia]
----
promote_rule(::Type{Float64}, ::Type{Int32}) = Float64
----

=== Meta-programação

O código Julia pode ser representado como uma estrutura de dados da própria linguagem. Isso permite que um programa transforme e gere seu próprio código.

==== Expressões

Todo programa do Julia começa como uma string:

[source,@julia-repl-test chap19]
----
julia> prog = "1 + 2"
"1 + 2"
----

A próxima etapa é analisar cada string em um objeto chamado _expression_, representado pelo tipo Julia +Expr+:
(((expressão)))(((Expr)))((("tipo", "Base", "Expr", see="Expr")))(((parse)))((("função", "Meta", "parse", see="parse")))

[source,@julia-repl-test chap19]
----
julia> ex = Meta.parse(prog)
:(1 + 2)
julia> typeof(ex)
Expr
julia> dump(ex)
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol +
    2: Int64 1
    3: Int64 2
----

A função +dump+ exibe objetos expr com anotações.
(((dump)))

Expressões podem ser construídas diretamente prefixando +:+ entre parênteses ou usando um bloco de aspas
(((:)))(((quote)))((("palavra-chave", "quote", see="quote")))

[source,@julia-repl-test chap19]
----
julia> ex = quote
           1 + 2
       end;
----

==== +eval+

O Julia pode avaliar um objeto de expressão usando +eval+:
(((eval)))((("função", "Core", "eval", see="eval")))

[source,@julia-eval chap19]
----
import Base.eval
----

[source,@julia-repl-test chap19]
----
julia> eval(ex)
3
----

Cada módulo possui sua própria função +eval+ que avalia expressões em seu escopo.

[WARNING]
====
Quando você está usando muitas chamadas para a função +eval+, geralmente isso significa que algo está errado. +eval+ é considerado "mal".
====

==== Macros

Macros podem incluir código gerado em um programa. Um _macro_ mapeia uma tupla de objetos +Expr+ diretamente para uma expressão compilada:
(((macro)))

Aqui está uma simples macro:
(((@containervariavel)))((("macro", "definido pelo programador", "@containervariavel", see="@containervariavel")))

[source,@julia-setup chap19]
----
macro containervariavel(container, elemento)
    return esc(:($(Symbol(container,elemento)) = $container[$elemento]))
end
----

As macros são chamadas com o prefixo +@+ (sinal de arroba). A chamada de macro +@containervariavel letters 1+ é substituída por:
(((@)))

[source,julia]
----
:(letters1 = letters[1])
----

+@macroexpand @containervariavel letters 1+ retorna essa expressão que é extremamente útil para depuração.
(((@macroexpand)))((("macro", "Base", "@macroexpand", see="@macroexpand")))

Este exemplo ilustra como uma macro pode acessar o nome de seus argumentos, algo que uma função não pode fazer. A expressão de retorno precisa ser "escapada" com +esc+, pois precisa ser resolvida no ambiente de chamada de macro.
(((esc)))((("função", "Base", "esc", see="esc")))

[NOTE]
====
Por que macros?

As macros geram e incluem fragmentos de código personalizado durante o tempo de análise, portanto, _antes_ que o programa completo seja executado.
====

==== Funções Geradas

A macro +@generated+ cria código especializado para métodos, dependendo dos tipos de argumentos:
(((funções geradas)))(((@generated)))((("macro", "Base", "@generated", see="@generated")))

[source,@julia-setup chap19]
----
@generated function square(x)
    println(x)
    :(x * x)
end
----

O corpo retorna uma expressão entre aspas como uma macro.

Para o chamador, a função _generated_ se comporta como uma função regular:

[source,@julia-repl-test chap19]
----
julia> x = square(2); # note: output é da declaração println() no corpo
Int64
julia> x              # agora imprimimos x
4
julia> y = square("spam");
String
julia> y
"spamspam"
----

=== Valores Ausentes

_Valores ausentes_ podem ser representados através do objeto +missing+, que é a instância singleton do tipo +Missing+.
(((valores ausentes)))(((missing)))(((Missing)))((("tipo", "Base", "Missing", see="Missing")))

As listas podem conter valores ausentes:

[source,@julia-repl-test chap19]
----
julia> a = [1, missing]
2-element Array{Union{Missing, Int64},1}:
 1
  missing
----

O tipo de elemento dessa lista é +Union{Missing, T}+, com +T+ o tipo de valores não ausentes.

As funções de redução retornam +missing+ quando chamadas em listas que contêm valores ausentes

[source,@julia-repl-test chap19]
----
julia> sum(a)
missing
----

Nessa situação, use a função +skipmissing+ para pular os valores ausentes:
(((skipmissing)))((("função", "Base", "skipmissing", see="skipmissing")))

[source,@julia-repl-test chap19]
----
julia> sum(skipmissing([1, missing]))
1
----


=== Chamando Códigos em C e Fortran

Muitos códigos estão escritos em C ou Fortran. Reutilizar o código testado geralmente é melhor do que escrever sua própria versão de um algoritmo. Julia pode chamar diretamente as bibliotecas C ou Fortran existentes usando a sintaxe +ccall+.
(((ccall)))((("função", "Base", "ccall", see="ccall")))

Em <<databases>>, introduzimos uma interface Julia na biblioteca GDBM de funções de banco de dados. A biblioteca está escrita em C. Para fechar o banco de dados, uma chamada de função para +close(db)+ deve ser feita:

[source,julia]
----
Base.close(dbm::DBM) = gdbm_close(dbm.handle)

function gdbm_close(handle::Ptr{Cvoid})
    ccall((:gdbm_close, "libgdbm"), Cvoid, (Ptr{Cvoid},), handle)
end
----

Um objeto dbm possui um campo +handle+ do tipo +Ptr{Cvoid}+. Este campo contém um ponteiro C que se refere ao banco de dados. Para fechar o banco de dados, a função C +gdbm_close+ deve ser chamada tendo como único argumento o ponteiro C apontando para o banco de dados e sem valor de retorno. O Julia faz isso diretamente com a função +ccall+ tendo como argumentos:
(((Ptr)))((("tipo", "Base", "Ptr", see="Ptr")))

* uma trupla que consiste em um símbolo que contém o nome da função que queremos chamar: +:gdbm_close+ e a biblioteca compartilhada especificada como uma sequência: +"libgdm"+,

* o tipo de retorno: +Cvoid+,

* uma tupla de tipos de argumentos: +(Ptr{Cvoid},)+ e

* os valores do argumento: +handle+.

O mapeamento completo da biblioteca GDBM pode ser encontrada como um exmplo nas fontes do JuliaIntroBR.

=== Glossário

fechamentos::
Função que captura variáveis de seu escopo definido.
(((fechamento)))

bloqueio let::
Bloqueia a alocação de novas ligações de variáveis.
(((bloqueio let)))

funções anônimas::
Função definida sem possuir nome.
(((função anônima)))

tupla nomeada::
Tupla com componentes nomeados.
(((tupla nomeada)))

argumentos de palavra-chave::
Argumentos identificados pelo nome em vez de apenas pela posição.
(((argumentos de palavra-chave)))

bloco do::
Construção de sintaxe usada para definir e chamar uma função anônima que se parece com um bloco de código normal.
(((bloco do)))

operador ternário::
Operador de fluxo de controle usando três operandos para especificar uma condição, uma expressão a ser executada quando a condição render +true+ e uma expressão a ser executada quando a condição render +false+.
(((operador ternário)))

avaliação de curto-circuíto::
Avaliação de um operador booleano para o qual o segundo argumento é executado ou avaliado apenas se o primeiro argumento não for suficiente para determinar o valor da expressão.
(((avaliação de curto-circuíto)))

tarefa (também conhecida como Corrotina)::
Recurso de fluxo de controle que permite que os cálculos sejam suspensos e retomados de maneira flexível.
(((tarefa)))

tipo primitivo::
Tipo de concreto cujos dados consistem em bits antigos simples.
(((tipo primitivo)))

tipo de união::
Tipo que inclui como objetos todas as instâncias de qualquer um dos seus parâmetros de tipo.
(((união de tipo)))

tipo paramétrico::
Tipo que está parametrizado.
(((tipo paramétrico)))

funtor::
Objeto com um método associado, para que ele possa ser chamado.
(((functor)))

conversão::
A conversão permite converter um valor de um tipo para outro.
(((conversão)))

promoção::
Conversão valores de tipos mistos em um único tipo comum.
(((promoção)))

expressão::
Tipo de Julia que contém uma construção de linguagem.
(((expressão)))

macro::
Forma de incluir o código gerado no corpo final de um programa.
(((macro)))

funções geradas::
Funções capazes de gerar código especializado, dependendo dos tipos dos argumentos.
(((funções geradas)))

valores ausentes::
Instâncias que representam pontos de dados sem valor.
(((valores ausentes)))
